

> Add blockquote

SIDDHANT SINHA 25070123109

EXP 14- DATA BINDING AND DATA FORMATTING USING PYTHON

In [5]:
import pandas as pd
import numpy as np
#conversion of numeric data to categorical data such as low medium high etc etc for different data.

data = {
'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
'Price':[55000,20000,30000,2000,8000,45000],
'Units_Sold':[25,60,35,80,50,15]
}

df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [6]:
#Data Binning
bins1=[0,10000,30000,60000]
labels1=['Cheap','Medium','Expensive']
df['Price_Category'] = pd.cut(df['Price'],bins=bins1, labels=labels1)

#pd.cut converts continous data tocategorical data

print(df)

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25      Expensive
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80          Cheap
4  Smartwatch   8000          50          Cheap
5      Camera  45000          15      Expensive

In [7]:
#Binning Units Sold
bins2=[0,15,30,60,100]
labels2=['Very Low Sales','Low Sales','Medium sales','High sales']
df['Sales_Category'] = pd.cut(df['Units_Sold'],bins=bins2, labels=labels2)
print(df)

      Product  Price  Units_Sold Price_Category  Sales_Category
0      Laptop  55000          25      Expensive       Low Sales
1      Mobile  20000          60         Medium    Medium sales
2      Tablet  30000          35         Medium    Medium sales
3  Headphones   2000          80          Cheap      High sales
4  Smartwatch   8000          50          Cheap    Medium sales
5      Camera  45000          15      Expensive  Very Low Sales

In [8]:
#Data Formatting
#Convert Data Type

print(df.dtypes)

#df['Units_Sold] = df['Units_Sold'].astype(float) #conversion of unit_sold from int to float
#print(df.dtypes)

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object

In [9]:
print(df.dtypes)

df['Units_Sold'] = df['Units_Sold'].astype(float)

#conversion of unit_sold from int to float shown here

print(df.dtypes)

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object
Product             object
Price                int64
Units_Sold         float64
Price_Category    category
Sales_Category    category
dtype: object

In [10]:
#Convert text to Uppercase
df['Product']= df['Product'].str.upper()
print(df)

      Product  Price  Units_Sold Price_Category  Sales_Category
0      LAPTOP  55000        25.0      Expensive       Low Sales
1      MOBILE  20000        60.0         Medium    Medium sales
2      TABLET  30000        35.0         Medium    Medium sales
3  HEADPHONES   2000        80.0          Cheap      High sales
4  SMARTWATCH   8000        50.0          Cheap    Medium sales
5      CAMERA  45000        15.0      Expensive  Very Low Sales

In [11]:
#Rounding Values
df['Price']=df['Price'].round(2)
df

      Product  Price  Units_Sold Price_Category  Sales_Category
0      LAPTOP  55000        25.0      Expensive       Low Sales
1      MOBILE  20000        60.0         Medium    Medium sales
2      TABLET  30000        35.0         Medium    Medium sales
3  HEADPHONES   2000        80.0          Cheap      High sales
4  SMARTWATCH   8000        50.0          Cheap    Medium sales
5      CAMERA  45000        15.0      Expensive  Very Low Sales

In [12]:
#Additional Operations
#Sort Data
sorted_df= df.sort_values(by='Price')    #(if you want data in same table then use inplace=True after Price)
print(sorted_df)

      Product  Price  Units_Sold Price_Category  Sales_Category
3  HEADPHONES   2000        80.0          Cheap      High sales
4  SMARTWATCH   8000        50.0          Cheap    Medium sales
1      MOBILE  20000        60.0         Medium    Medium sales
2      TABLET  30000        35.0         Medium    Medium sales
5      CAMERA  45000        15.0      Expensive  Very Low Sales
0      LAPTOP  55000        25.0      Expensive       Low Sales

In [13]:
sorted_df= df.sort_values(by='Price',ascending=False) #Converts in descending order
print(sorted_df)

      Product  Price  Units_Sold Price_Category  Sales_Category
0      LAPTOP  55000        25.0      Expensive       Low Sales
5      CAMERA  45000        15.0      Expensive  Very Low Sales
2      TABLET  30000        35.0         Medium    Medium sales
1      MOBILE  20000        60.0         Medium    Medium sales
4  SMARTWATCH   8000        50.0          Cheap    Medium sales
3  HEADPHONES   2000        80.0          Cheap      High sales

In [14]:
#Display Unique Values
print(df['Price_Category'].unique())

['Expensive', 'Medium', 'Cheap']
Categories (3, object): ['Cheap' < 'Medium' < 'Expensive']

In [15]:
#Dataset: Food Delivery Orders
#Do all above function here also

import pandas as pd
import numpy as np

data = {
'Order_ID':['O1','O2','O3','O4','O5','O6','O7','O8'],
'Order_Value':[250,450,120,600,300,150,500,220],
'Delivery_Time':[30,45,25,60,35,20,50,28],
'Distance_km':[5,8,3,10,6,2,9,4]
}

df = pd.DataFrame(data)

print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km
0       O1          250             30            5
1       O2          450             45            8
2       O3          120             25            3
3       O4          600             60           10
4       O5          300             35            6
5       O6          150             20            2
6       O7          500             50            9
7       O8          220             28            4

In [16]:
#Binning Order Value
bins=[0,200,400,700]
labels=['Low Order','Medium Order','High Order']
df['Order_Category']=pd.cut(df['Order_Value'],bins=bins,labels=labels)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category
0       O1          250             30            5   Medium Order
1       O2          450             45            8     High Order
2       O3          120             25            3      Low Order
3       O4          600             60           10     High Order
4       O5          300             35            6   Medium Order
5       O6          150             20            2      Low Order
6       O7          500             50            9     High Order
7       O8          220             28            4   Medium Order

In [17]:
#Count of categories
print(df['Order_Category'].value_counts())
df

Order_Category
Medium Order    3
High Order      3
Low Order       2
Name: count, dtype: int64

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category
0       O1          250             30            5   Medium Order
1       O2          450             45            8     High Order
2       O3          120             25            3      Low Order
3       O4          600             60           10     High Order
4       O5          300             35            6   Medium Order
5       O6          150             20            2      Low Order
6       O7          500             50            9     High Order
7       O8          220             28            4   Medium Order

In [23]:
#Binning dilivery time
bins3=[0,25,45,65]
labels3=['Fast','Medium','Slow']
df['Delivery_Category']=pd.cut(df['Delivery_Time'],bins=bins3,labels=labels3)

print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
5       O6          150             20            2      Low Order
2       O3          120             25            3      Low Order
7       O8          220             28            4   Medium Order
0       O1          250             30            5   Medium Order
4       O5          300             35            6   Medium Order
1       O2          450             45            8     High Order
6       O7          500             50            9     High Order
3       O4          600             60           10     High Order

  Delivery_Category Distance_Category
5              Fast              near
2              Fast              near
7            Medium            medium
0            Medium            medium
4            Medium            medium
1            Medium               far
6              Slow               far
3              Slow               far

In [22]:
#Binning distance
bins4=[0,3,7,11]
labels4=['near','medium','far']
df['Distance_Category']=pd.cut(df['Distance_km'],bins=bins4,labels=labels4)

print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
5       O6          150             20            2      Low Order
2       O3          120             25            3      Low Order
7       O8          220             28            4   Medium Order
0       O1          250             30            5   Medium Order
4       O5          300             35            6   Medium Order
1       O2          450             45            8     High Order
6       O7          500             50            9     High Order
3       O4          600             60           10     High Order

  Delivery_Category Distance_Category
5              Fast              near
2              Fast              near
7            Medium            medium
0            Medium            medium
4            Medium            medium
1            Medium               far
6              Slow               far
3              Slow               far

In [24]:
#counting the value of categories
print(df['Order_Category'].value_counts())
print()
print(df['Delivery_Category'].value_counts())
print()
print(df['Distance_Category'].value_counts())

Order_Category
Medium Order    3
High Order      3
Low Order       2
Name: count, dtype: int64

Delivery_Category
Medium    4
Fast      2
Slow      2
Name: count, dtype: int64

Distance_Category
medium    3
far       3
near      2
Name: count, dtype: int64

In [25]:
#Data formatng
# Convert Data type

print(df.dtypes)

df['Delivery_Time']=df['Delivery_Time'].astype(float)
print(df.dtypes)
print()
print("updates table:")
print(df)

Order_ID               object
Order_Value             int64
Delivery_Time           int64
Distance_km             int64
Order_Category       category
Delivery_Category    category
Distance_Category    category
dtype: object
Order_ID               object
Order_Value             int64
Delivery_Time         float64
Distance_km             int64
Order_Category       category
Delivery_Category    category
Distance_Category    category
dtype: object

updates table:
  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
5       O6          150           20.0            2      Low Order
2       O3          120           25.0            3      Low Order
7       O8          220           28.0            4   Medium Order
0       O1          250           30.0            5   Medium Order
4       O5          300           35.0            6   Medium Order
1       O2          450           45.0            8     High Order
6       O7          500           50.0            9     High Order
3       O4          600           60.0           10     High Order

  Delivery_Category Distance_Category
5              Fast              near
2              Fast              near
7            Medium            medium
0            Medium            medium
4            Medium            medium
1            Medium               far
6              Slow               far
3              Slow               far